import { Injectable } from '@nestjs/common';
import { Pool } from 'pg';
import { exec } from 'child_process';

/**
 * PostgresAdminService — Tenant database lifecycle management.
 *
 * Uses a short-lived pg.Pool connected to the 'postgres' maintenance database
 * for CREATE/DROP DATABASE operations. Migrations are run via `prisma migrate
 * deploy` with a DATABASE_URL pointing to the tenant database.
 */
@Injectable()
export class PostgresAdminService {
  private readonly pool: Pool;
  private readonly masterDbUrl: string;

  constructor() {
    this.masterDbUrl = process.env.MASTER_DATABASE_URL ?? '';
    // Connect to the 'postgres' maintenance database (derived from master URL)
    const postgresUrl = this.masterDbUrl.replace(/\/[^/]+$/, '/postgres');
    this.pool = new Pool({ connectionString: postgresUrl });
  }

  /**
   * Creates a new PostgreSQL database.
   *
   * @param dbName — Must be a safe identifier (alphanumeric + underscore only).
   *                 Generated by the domain as `educandow_{uuid}`.
   */
  async createDatabase(dbName: string): Promise<void> {
    // PostgreSQL identifiers are quoted with double-quotes.
    // The dbName is validated to contain only safe characters.
    await this.pool.query(`CREATE DATABASE "${dbName}"`);
  }

  /**
   * Drops a PostgreSQL database if it exists.
   *
   * Errors are swallowed — the DB may not exist and that is acceptable
   * during rollback scenarios.
   */
  async dropDatabase(dbName: string): Promise<void> {
    try {
      await this.pool.query(`DROP DATABASE IF EXISTS "${dbName}"`);
    } catch {
      // Silently ignore — the database may already be gone
    }
  }

  /**
   * Runs Prisma migrations against the tenant database.
   *
 * Uses `prisma migrate deploy` (idempotent, handles locking) with
 * a DATABASE_URL pointing to the tenant DB. The schema path is
 * `prisma_tenant/schema.prisma`.
   */
  async runTenantMigrations(dbName: string): Promise<void> {
    const tenantUrl = this.masterDbUrl.replace(/\/[^/]+$/, `/${dbName}`);

    return new Promise((resolve, reject) => {
      exec(
        'npx prisma migrate deploy --schema=prisma_tenant/schema.prisma',
        {
          env: {
            ...process.env,
            DATABASE_URL: tenantUrl,
          },
        },
        (error, _stdout, stderr) => {
          if (error) {
            reject(new Error(`Migration failed: ${stderr || error.message}`));
          } else {
            resolve();
          }
        },
      );
    });
  }
}
