export { Subject } from './entities/subject';
export type { SubjectProps } from './entities/subject';
export { CourseSection } from './entities/course-section';
export type { CourseSectionProps } from './entities/course-section';
export { SubjectAssignment } from './entities/subject-assignment';
export type { SubjectAssignmentProps } from './entities/subject-assignment';
export { Evaluacion } from './entities/evaluacion';
export type { EvaluacionProps } from './entities/evaluacion';
export { Nota } from './entities/nota';
export type { NotaProps } from './entities/nota';
export { PeriodoEvaluacion } from './entities/periodo-evaluacion';
export type { PeriodoEvaluacionProps } from './entities/periodo-evaluacion';
export { NotaTrimestral } from './entities/nota-trimestral';
export type { NotaTrimestralProps } from './entities/nota-trimestral';
export { Attendance } from './entities/attendance';
export type { AttendanceProps, AttendanceStatusCode, AttendanceStatusEntity } from './entities/attendance';
export { GradeScale, GradeScaleValue } from './entities/grade-scale';
export type { GradeScaleProps, GradeScaleValueProps } from './entities/grade-scale';

export type { SubjectRepository } from './repositories/subject-repository';
export type { CourseSectionRepository } from './repositories/course-section-repository';
export type { SubjectAssignmentRepository } from './repositories/subject-assignment-repository';
export type { EvaluacionRepository } from './repositories/evaluacion-repository';
export type { NotaRepository } from './repositories/nota-repository';
export type { PeriodoEvaluacionRepository } from './repositories/periodo-evaluacion-repository';
export type { NotaTrimestralRepository } from './repositories/nota-trimestral-repository';
export type { AttendanceRepository } from './repositories/attendance-repository';
export type { GradeScaleRepository } from './repositories/grade-scale-repository';
