export { User } from './entities/user';
export type { UserRole, ModuleAccess } from './entities/user';
export { Role } from './entities/role';
export { Module } from './entities/module';
export { ModuleAction } from './entities/module-action';
export { Password } from './value-objects/password';
export type { UserRepository } from './repositories/user-repository';
export type { RefreshTokenRepository, RefreshTokenData } from './repositories/refresh-token-repository';
export { UserRegistered } from './events/user-registered';
export { UserNotFoundError, EmailAlreadyExistsError, InvalidCredentialsError } from './errors/user.errors';
export { ROLE_HIERARCHY, ROLE_LABELS, getHighestRoleRank, canManageUser, canViewUser } from './role-hierarchy';
